name: Sync Notion Notes

on:
  schedule:
    - cron: '0 8 * * *'  # Codziennie o 8:00 UTC
  workflow_dispatch:  # Możliwość uruchomienia ręcznego
  repository_dispatch:  # Webhook trigger
    types: [notion_webhook]

jobs:
  sync-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install @notionhq/client
          npm install notion-to-md
          
      - name: Sync from Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          node sync-script.js
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Auto-sync notes from Notion $(date)"
          git push
